services:

  amazeeio-dnsmasq:
    image: ghcr.io/pygmystack/dnsmasq:main
    Config:
      Labels:
        - pygmy.hocuspocus: 42
        - pygmy.abracadabra: true
        - pygmy.opensesame: correct

  amazeeio-haproxy:
    Config:
      Labels:
        - pygmy.hocuspocus: 42
        - pygmy.abracadabra: true
        - pygmy.opensesame: correct

  amazeeio-mailhog:
    Config:
      Labels:
        - pygmy.hocuspocus: 42
        - pygmy.abracadabra: true
        - pygmy.opensesame: correct

  amazeeio-ssh-agent:
    Config:
      Labels:
        - pygmy.hocuspocus: 42
        - pygmy.abracadabra: true
        - pygmy.opensesame: correct

  amazeeio-ssh-agent-add-key:
    Config:
      Labels:
        - pygmy.enable: false
