name: Build, Test & Publish

on:
  push:
    branches:
      - "main"
      - "dev"
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  ci:
    uses: pygmystack/.github/.github/workflows/container-build-test-publish.yml@legacy-name
    with:
      image_name: dns
      image_name_legacy: dnsmasq
      replace_source: ghcr.io/pygmystack/dnsmasq:main
      oc_authors: the pygmy stack, Simon Kelley (dnsmasq)
      oc_description: dnsmasq DNS proxy, configured for use with the pygmy stack
    secrets: inherit
